DROP TABLE ALUNO;
DROP TABLE ENDERECO;
/*
    COLOCAMOS O ENDEREÇO PRIMEIRO DE ALUNO POIS A TABELA ALUNO PRECISA TER A
    REFERENCIA DO ENDEREÇO PARA TER A INTEREGRAÇÃO E O MODELO LOGICO SENDO
    CRIADO DE FORMA CORRETA PARA VISUALIZAÇÃO IGUAL A DA DATA MODELER
*/
CREATE TABLE ENDERECO (
    CEP INT PRIMARY KEY,
    RUA VARCHAR(100),
    CIDADE VARCHAR(100),
    UF VARCHAR(2)
);

CREATE TABLE ALUNO(
    RA INT,
    NOME VARCHAR(60) CONSTRAINT NN_NOME NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(14) UNIQUE,
    -- REFERENCIA DA TABELA ENDERECO CITADA ACIMA --
    CEP INT REFERENCES ENDERECO(CEP),
    CONSTRAINT PK_RA PRIMARY KEY (RA)    
);