-- APAGANDO A TABELA --

DROP TABLE ALUNO;
DROP TABLE ENDERECO;
DROP TABLE PROFESSOR;




--CRIANDO TABELA SEM CONSTRAINT--

CREATE TABLE ALUNO(
    RA INT,
    NOME VARCHAR(60),
    DT_NASCIMENTO DATE
);

--CRIANDO TABELA COM CONSTRAINT--

CREATE TABLE ALUNO(
    RA INT,
    NOME VARCHAR(60) CONSTRAINT NN_NOME NOT NULL,
    DT_NASCIMENTO DATE NOT NULL
);


CREATE TABLE ALUNO(
    RA INT PRIMARY KEY ,
    NOME VARCHAR(60) CONSTRAINT NN_NOME NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(14) UNIQUE 
);

CREATE TABLE ENDERECO (
    CEP INT PRIMARY KEY,
    RUA VARCHAR(100),
    CIDADE VARCHAR(100),
    UF VARCHAR(2)
);

CREATE TABLE ALUNO(
    RA INT,
    NOME VARCHAR(60) CONSTRAINT NN_NOME NOT NULL,
    DT_NASCIMENTO DATE NOT NULL,
    CPF VARCHAR(14) UNIQUE,
    -- REFERENCIA DA TABELA ENDERECO CITADA ACIMA --
    CEP INT REFERENCES ENDERECO(CEP),
    CONSTRAINT PK_RA PRIMARY KEY (RA)    
);




